#include "CBController.h"

#include <QSettings>
#include <QtWidgets/QApplication>

#include "CBUtils.h"
#include "CBTranslator.h"

const QString kSettingBasePath="global/base";
const QString kSettingCollectAutogenerated="global/needCollect";

CBController::CBController(QObject *parent) : QObject(parent)
{
    m_baseProvider= NULL;
}


void CBController::start(){
    QString basePath;
    QSettings settings("settings.ini",QSettings::IniFormat);
    settings.setIniCodec("windows-1251");

    basePath=settings.value(kSettingBasePath,"").toString();

    if (basePath.isEmpty()){
        QMetaObject::invokeMethod(this->applicationWindow,
                                  "openBase"
                                  );
    }
    else {
        try {
            this->openBase(basePath);
        }
        catch (...) {
            QMetaObject::invokeMethod(this->applicationWindow,
                                      "openBaseAlert"
                                      );
        }
    }

}

void CBController::openBase(QString basePath){


    QSettings settings("settings.ini",QSettings::IniFormat);
    settings.setIniCodec("windows-1251");
    settings.setValue(kSettingBasePath,QVariant(basePath));

    QVariant var = settings.value(kSettingCollectAutogenerated,false);
    bool needCollect = var.toBool();

    this->applicationWindow->setProperty("needCollect", var);

    if (m_baseProvider) {
        delete m_baseProvider;
    }

    CBUtils::FromQmlFilePath(&basePath);

    // load translator for specific base termins (mostly fieldnames)
    // FIXME: Need 2 translator - one for base termins (this one) and one for system messages

    QString locale = QLocale::system().name();
    QString filename = QString("languages/") + locale+".json";
    static CBTranslator translator;
    translator.m_needCollect = needCollect;
    if( translator.load(filename, basePath) ){
        QApplication::instance()->installTranslator(&translator);
        //QTextCodec::setCodecForTr(QTextCodec::codecForName("utf8"));
        qDebug() << "Translation file loaded" << filename;
    } else
        qDebug() << "Translation file not loaded:" << filename << "  dir:"<<basePath;



    m_baseProvider=new CBBaseProvider();
    this->connect(m_baseProvider,SIGNAL(readyToWork()),this,SLOT(providerReadyToWork()));
    m_baseProvider->startWithPath(basePath);
}

void CBController::providerReadyToWork(){
//    engine->addImageProvider(QLatin1String("imageProvider"),m_baseProvider->imageProvider);
    QMetaObject::invokeMethod(this->applicationWindow,
                              "providerReadyToWork"
                              );
}
